name: ebisu_pod
version: 0.0.11
author: Daniel Davidson <dbdavidson@yahoo.com>
homepage: https://github.com/patefacio/ebisu_pod
description: >
  A general purpose *recursive design pattern* for modeling plain old
  data components. Think *IDL*, or *json schema* but only covering the
  basic data modeling of scalars, arrays, and dictionaries
  (a.k.a. objects).

  The goal is a simple modeling API that can then be used as inputs to
  code generators.

environment:
  sdk: '>=2.0.0-dev.61 <3.0.0'

dependencies:

# custom <ebisu_pod dependencies>

  collection: "1.14.11"
  ebisu:
    git: git://github.com/patefacio/ebisu.git
  ebisu_cpp:
    git: git://github.com/patefacio/ebisu_cpp.git

  ebisu_rs:
    git: git://github.com/patefacio/ebisu_rs

  id:
    git: git://github.com/patefacio/id.git

  quiver: "2.0.0+1"
  logging: "0.11.3+2"
  path: "^1.4.1"  
    
# end <ebisu_pod dependencies>

dev_dependencies:

# custom <ebisu_pod dev dependencies>

  test: "^1.3.0"
  
# end <ebisu_pod dev dependencies>

dependency_overrides:
# custom <ebisu_pod dependency overrides>
      
# end <ebisu_pod dependency overrides>

transformers:

# custom <ebisu_pod transformers>
# end <ebisu_pod transformers>

