name: ebisu_pod
version: 0.0.11
author: Daniel Davidson <dbdavidson@yahoo.com>
homepage: https://github.com/patefacio/ebisu_pod
description: >
  A general purpose *recursive design pattern* for modeling plain old
  data components. Think *IDL*, or *json schema* but only covering the
  basic data modeling of scalars, arrays, and dictionaries
  (a.k.a. objects).

  The goal is a simple modeling API that can then be used as inputs to
  code generators.

environment:
  sdk: '>=1.8.2 <2.0.0'

dependencies:

# custom <ebisu_pod dependencies>

  collection: ">=1.1.0<1.14.0"
  ebisu: "^0.7.5"
  ebisu_cpp: "^0.3.25"
  ebisu_rs:
    path: ../ebisu_rs
  id: "^1.0.16"
  logging: ">=0.9.3<0.12.0"
  quiver: ">=0.21.0<0.25.0"
  path: "^1.4.1"  
    
# end <ebisu_pod dependencies>

dev_dependencies:

# custom <ebisu_pod dev dependencies>

  test: ">=0.12.0 < 0.14.0"
  
# end <ebisu_pod dev dependencies>

dependency_overrides:
# custom <ebisu_pod dependency overrides>
      
# end <ebisu_pod dependency overrides>

transformers:

# custom <ebisu_pod transformers>
# end <ebisu_pod transformers>

